# Generated by Django 6.0.5 on 2026-06-18 23:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='По батькові')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Область')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='Аватар')),
                ('is_verified_seller', models.BooleanField(default=False, verbose_name='Верифікований продавець')),
                ('years_on_site', models.CharField(blank=True, max_length=20, verbose_name='Років на сайті')),
                ('last_online', models.DateTimeField(blank=True, null=True, verbose_name='Останній раз онлайн')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Рік')),
                ('generation', models.CharField(blank=True, max_length=100, verbose_name='Покоління')),
                ('modification', models.CharField(blank=True, max_length=100, verbose_name='Модифікація')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна USD')),
                ('price_uah', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна UAH')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стара ціна')),
                ('credit_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Кредит/міс')),
                ('mileage', models.IntegerField(verbose_name='Пробіг (тис. км)')),
                ('engine', models.CharField(max_length=100, verbose_name='Двигун')),
                ('engine_volume', models.CharField(blank=True, max_length=20, verbose_name="Об'єм двигуна")),
                ('hp', models.IntegerField(blank=True, null=True, verbose_name='К.с.')),
                ('transmission', models.CharField(max_length=50, verbose_name='КПП')),
                ('body_type', models.CharField(blank=True, max_length=50, verbose_name='Тип кузова')),
                ('doors', models.IntegerField(default=4, verbose_name='Двері')),
                ('seats', models.IntegerField(default=5, verbose_name='Місця')),
                ('drive', models.CharField(blank=True, max_length=50, verbose_name='Привід')),
                ('eco_standard', models.CharField(blank=True, max_length=50, verbose_name='Екостандарт')),
                ('fuel_city', models.FloatField(blank=True, null=True, verbose_name='Витрата місто')),
                ('fuel_highway', models.FloatField(blank=True, null=True, verbose_name='Витрата траса')),
                ('fuel_mixed', models.FloatField(blank=True, null=True, verbose_name='Витрата змішаний')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Колір')),
                ('color_hex', models.CharField(blank=True, max_length=7, verbose_name='Колір HEX')),
                ('interior_color', models.CharField(blank=True, max_length=50, verbose_name='Колір салону')),
                ('interior_material', models.CharField(blank=True, max_length=50, verbose_name='Матеріал салону')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Область')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='Індекс')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='VIN')),
                ('plate', models.CharField(blank=True, max_length=20, verbose_name='Держномер')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='cars/', verbose_name='Головне фото')),
                ('owners', models.IntegerField(default=1, verbose_name='Власників')),
                ('state', models.CharField(blank=True, max_length=200, verbose_name='Стан')),
                ('safety', models.TextField(blank=True, verbose_name='Безпека')),
                ('comfort', models.TextField(blank=True, verbose_name='Комфорт')),
                ('multimedia', models.TextField(blank=True, verbose_name='Мультимедіа')),
                ('headlights', models.CharField(blank=True, max_length=100, verbose_name='Фари')),
                ('conditioning', models.CharField(blank=True, max_length=100, verbose_name='Кондиціонер')),
                ('power_steering', models.CharField(blank=True, max_length=50, verbose_name='Підсилювач керма')),
                ('steering_adjustment', models.CharField(blank=True, max_length=100, verbose_name='Регулювання керма')),
                ('spare_wheel', models.CharField(blank=True, max_length=50, verbose_name='Запасне колесо')),
                ('optics', models.TextField(blank=True, verbose_name='Оптика')),
                ('parking_help', models.TextField(blank=True, verbose_name='Допомога при паркуванні')),
                ('airbags', models.TextField(blank=True, verbose_name='Подушки безпеки')),
                ('electric_windows', models.CharField(blank=True, max_length=100, verbose_name='Електросклопідйомники')),
                ('seat_adjustment', models.CharField(blank=True, max_length=200, verbose_name='Регулювання сидінь')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Теги')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Продавець')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
                'db_table': 'cars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='autoria.car', verbose_name='Автомобіль')),
            ],
            options={
                'verbose_name': 'Фото автомобіля',
                'verbose_name_plural': 'Фото автомобілів',
                'db_table': 'car_images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='autoria.car', verbose_name='Автомобіль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Обране',
                'verbose_name_plural': 'Обране',
                'db_table': 'favorites',
                'unique_together': {('user', 'car')},
            },
        ),
    ]
