# Generated by Django 6.0.5 on 2026-06-19 23:57

import autoria.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, storage=autoria.storage.CloudinaryStorage(folder='cars'), upload_to='cars/', verbose_name='Головне фото'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(storage=autoria.storage.CloudinaryStorage(folder='cars/gallery'), upload_to='cars/gallery/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, storage=autoria.storage.CloudinaryStorage(folder='avatars'), upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
